// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(TenderCareDbContext))]
    [Migration("20260112143714_FinalFix")]
    partial class FinalFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project.Models.Appointment", b =>
                {
                    b.Property<string>("AppointmentID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ServiceType")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("AppointmentID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Project.Models.Immunization", b =>
                {
                    b.Property<string>("ImmunizationID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateAdministered")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DoseNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("VaccineName")
                        .HasColumnType("longtext");

                    b.HasKey("ImmunizationID");

                    b.HasIndex("PatientID");

                    b.ToTable("Immunization", (string)null);
                });

            modelBuilder.Entity("Project.Models.MedicalRecord", b =>
                {
                    b.Property<string>("RecordID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorName")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ServiceType")
                        .HasColumnType("longtext");

                    b.HasKey("RecordID");

                    b.HasIndex("PatientID");

                    b.ToTable("MedicalRecords", (string)null);
                });

            modelBuilder.Entity("Project.Models.Patient", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PatientID");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Project.Models.Appointment", b =>
                {
                    b.HasOne("Project.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Project.Models.Immunization", b =>
                {
                    b.HasOne("Project.Models.Patient", "Patient")
                        .WithMany("Immunizations")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Project.Models.MedicalRecord", b =>
                {
                    b.HasOne("Project.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Project.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Immunizations");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
